theme: jekyll-theme-midnight
title: "Ben's Technology Notebook"
description: "The project logs, technical runbooks, and problem-solving notes behind Ben’s engineering builds."

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
